[README] Added workaround for old opset versions
ENOT-AutoDL/onnx2torch pull request #130
Opened 2023-02-03 12:35 UTC by SuperSecureHuman

Model version conversion with onnx's python API for supporting some models.

Tested with 

mobilenetv2-7
resnet101-v1-7.onnx
resnet50-caffe2-v1-6.onnx

2023-02-04 15:30 UTC, senysenyseny16 requested changes
Hello, @SuperSecureHuman.

Thanks for your contribution!

Could you fix the code to match our code style?

2023-02-04 15:30 UTC, senysenyseny16 commented on README.md
> +model = onnx.load("model.onnx")
```suggestion
model = onnx.load('model.onnx')
```

2023-02-04 15:30 UTC, senysenyseny16 commented on README.md
> +torch.save(torch_model, "model.pt")
```suggestion
torch.save(torch_model, 'model.pt')
```

2023-02-05 14:45 UTC, SuperSecureHuman commented on README.md
> +Incase you are using a model with older opset, try the following workaround
Added 

https://github.com/ENOT-AutoDL/onnx2torch/pull/130/commits/3063242050f31e0cdc73d60f622fb13791b46f44

2023-02-05 17:06 UTC, senysenyseny16 approved these changes
Thanks!

2023-02-05 17:07 UTC, merged