Feat: preserve unique onnx node names
ENOT-AutoDL/onnx2torch pull request #140
Opened 2023-02-17 13:12 UTC by jan-haug

Currently, each ONNX node is assigned a unique name consisting of the domain, op_type and a running counter to name the torch module with: https://github.com/ENOT-AutoDL/onnx2torch/blob/main/onnx2torch/onnx_graph.py#L29-L34

However, it can be useful to be able to infer the torch module from the onnx graph after loading it, say for example if you want to modify something specifically in the conv-layers in the head of the network. Since torch 1.13, the names of the onnx nodes are also inferred from the namescopes (see https://github.com/pytorch/pytorch/issues/75100), so being able to match that makes finding modules after a torch-onnx-torch round extremely easy.

This change replaces the previous naming scheme with one based on the onnx node names, modifying them only when and as far as necessary:
- Dots `.` are not allowed as names, so they are replaced with a slash `/`. They occur when you export e.g. a `ModuleList` or `Sequential` from torch. Colons `:` are fine and don't need handling
- If for some reason, there are duplicate node names, a running counter is appended with an underscore. This keeps the existing counter, but doesn't append anything on the first occurence to keep the name if possible. Generally, node names are required to be unique in the ONNX standard anyways, but nothing prevents you from creating a graph with duplicate names, so why not account for it anyways.
- If for some reason, the name is empty, it will use the op_type as a fallback, so basically the old behavior
- `domain` is prepended and separated by a slash, too. Not sure if that is needed, in my use-cases `domain` is empty anyways

Example screenshots from inspecting the modules after loading a cifar100 resnet:
<details>
<summary>Before:</summary>
<img src="https://user-images.githubusercontent.com/18348021/219619250-825ddb75-d920-4318-8b1d-95ba90969e74.png"/>
</details>
<details>
<summary>After:</summary>
<img src="https://user-images.githubusercontent.com/18348021/219616133-faf0afd4-7283-44d0-a47c-3221d160f796.png"/>
</details>

Also, I'm assuming the existing tests are enough to make sure this doesn't actually break things. Should I add a test to make sure it actually works as expected?

2023-02-20 05:40 UTC, senysenyseny16 commented
Hi, @jan-haug.

Thanks for your PR.
New naming scheme looks nice!

Could you create separate function for node name generation?

Something like this:
```python3
@staticmethod
def generate_name(node: NodeProto) -> str:
    ...
```

2023-02-21 10:26 UTC, jan-haug commented
@senysenyseny16 Thank you!
Like this? https://github.com/ENOT-AutoDL/onnx2torch/pull/140/commits/b2c770ac9bc6576dd3c994b2644fb64c80b0a1ea

2023-02-27 09:33 UTC, senysenyseny16 requested changes

2023-02-27 09:33 UTC, senysenyseny16 commented on onnx2torch/onnx_graph.py
> +        return (f'{node.domain}/' + (node.name.replace(".", "/") or node.op_type)).lstrip("/")
```suggestion
        return (f'{node.domain}/' + (node.name.replace('.', '/') or node.op_type)).lstrip('/')
```

2023-02-27 09:36 UTC, senysenyseny16 commented on onnx2torch/onnx_graph.py
> +        return (f'{node.domain}/' + (node.name.replace(".", "/") or node.op_type)).lstrip("/")
Could you fix imports style?

2023-03-02 12:28 UTC, jan-haug commented on onnx2torch/onnx_graph.py
> +        return (f'{node.domain}/' + (node.name.replace(".", "/") or node.op_type)).lstrip("/")
Good catch! I added that :)

2023-03-14 19:43 UTC, ivkalgin approved these changes

2023-03-14 19:47 UTC, senysenyseny16 commented
@jan-haug Thank you!

2023-03-14 19:48 UTC, merged