bugfix: ReduceSumStaticAxes type correction
ENOT-AutoDL/onnx2torch pull request #171
Opened 2023-08-06 02:52 UTC by francis2tm

Hello,

**Bug details:**
```
File "onnx2torch/onnx2torch/node_converters/reduce.py", line 159, in forward
    return torch.sum(input_tensor, dim=self._axes, keepdim=self._keepdims)
TypeError: sum() received an invalid combination of arguments - got (Tensor, keepdim=int, dim=list), but expected one of:
 * (Tensor input, *, torch.dtype dtype)
      didn't match because some of the keywords were incorrect: keepdim, dim
 * (Tensor input, tuple of ints dim, bool keepdim, *, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of names dim, bool keepdim, *, torch.dtype dtype, Tensor out)
 ```
**Args/Attrs to reproduce**
`input_tensor.shape`: `torch.Size([1, 8, 8, 65])`
`self._axes`: `[1, 2] <class 'list'>`
`self._keepdims`: `0` <class 'int'>`

My solution is a simple typecast. Only tested against my particular example.

2023-10-09 21:11 UTC, senysenyseny16 requested changes
hi, @francis2tm

2023-10-09 21:11 UTC, senysenyseny16 commented on pyproject.toml
> +    'onnxruntime>=1.15.1',
```suggestion
```

2023-10-09 21:11 UTC, senysenyseny16 commented on onnx2torch/node_converters/reduce.py
> +        return torch.sum(input_tensor, dim=tuple(self._axes), keepdim=bool(self._keepdims))
Could you please explain why `self._axes` should be wrapped into tuple?

2024-01-25 19:10 UTC, sniklaus commented
I had the very same error message and for me the `bool(...)` was sufficient, I didn't need the `tuple(...)`.

2024-03-25 10:36 UTC, Sbisseb commented
I am also using `return torch.sum(input_tensor, dim=self._axes, keepdim=bool(self._keepdims))` but I am now getting issues in `onnx2torch/node_converters/gather.py` in the slicing I am not sure why
```
return input_tensor[slice_for_take]
IndexError: index 4 is out of bounds for dimension 0 with size 3
```
Would you have any idea how to fix that?

2024-03-29 20:01 UTC, senysenyseny16 commented
https://github.com/ENOT-AutoDL/onnx2torch/pull/206

2024-03-29 20:01 UTC, closed without merging

2024-03-29 20:03 UTC, senysenyseny16 commented
> I am also using `return torch.sum(input_tensor, dim=self._axes, keepdim=bool(self._keepdims))` but I am now getting issues in `onnx2torch/node_converters/gather.py` in the slicing I am not sure why
> 
> ```
> return input_tensor[slice_for_take]
> IndexError: index 4 is out of bounds for dimension 0 with size 3
> ```
> 
> Would you have any idea how to fix that?

Hi, could you please open an issue with instructions for reproducing?